spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: james629203

#JPA Settings
  jpa.hibernate.ddl_auto: create